"""create tables

Revision ID: 338643ebd56a
Revises: f424111d3be7
Create Date: 2023-06-15 20:51:12.918262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338643ebd56a'
down_revision = 'f424111d3be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
