"""create tables

Revision ID: f424111d3be7
Revises: 2d593df72b01
Create Date: 2023-06-15 20:50:06.378881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f424111d3be7'
down_revision = '2d593df72b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Activity', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_signups_Activity_activities'), 'activities', ['Activity'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_signups_Activity_activities'), type_='foreignkey')
        batch_op.drop_column('Activity')

    # ### end Alembic commands ###
